name = "SnapshotTesting"
uuid = "cf213a48-8697-4c15-82cb-081f2086cf9e"
authors = ["Nathan Daly <nhdaly@gmail.com> and contributors"]
version = "0.3.0"

[deps]
DeepDiffs = "ab62b9b5-e342-54a8-a765-a90f495de1a6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DeepDiffs = "1"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
